## setup

In [ ]:
# %pip install vaderSentiment

# import stuff
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

### patient data

In [2]:
# load kaggle patient data
patient = pd.read_excel('data/patient_feedback_dataset.xlsx')

print('Shape:', patient.shape)
patient.head()

Shape: (1000, 5)

,Theme,Feedback,Sentiment,Satisfaction,Readmission
0,discharge,Discharge instructions were very clear,1,4,1
1,communication,I felt the doctor used too much medical jargon,1,5,0
2,medication,I appreciated the reminders about my medicines,1,4,0
3,discharge,Instructions after discharge were not helpful,0,1,1
4,discharge,Instructions after discharge were not helpful,0,2,1

In [3]:
patient.describe()
# sentiment is binary
# satisfaction scale 1-5

        Sentiment  Satisfaction  Readmission
count  1000.00000   1000.000000  1000.000000
mean      0.58400      3.418000     0.288000
std       0.49314      1.493153     0.453058
min       0.00000      1.000000     0.000000
25%       0.00000      2.000000     0.000000
50%       1.00000      4.000000     0.000000
75%       1.00000      5.000000     1.000000
max       1.00000      5.000000     1.000000

In [4]:
patient['Sentiment'].value_counts()

Sentiment
1    584
0    416
Name: count, dtype: int64

In [5]:
patient['Satisfaction'].value_counts()

Satisfaction
5    326
4    258
1    174
2    144
3     98
Name: count, dtype: int64

In [6]:
patient.groupby('Theme')[['Sentiment', 'Satisfaction']].mean()

               Sentiment  Satisfaction
Theme
communication   0.779026      3.977528
discharge       0.563025      3.373950
medication      0.606695      3.451883
wait_time       0.378906      2.843750

### yelp data

In [7]:
yelp = pd.read_csv("data/Yelp Restaurant Reviews.csv")

print('Shape:', yelp.shape)
yelp.head()

Shape: (19896, 4)

,Yelp URL,Rating,Date,Review Text
0,https://www.yelp.com/biz/sidney-dairy-barn-sidney,5,1/22/2022,All I can say is they have very good ice cream...
1,https://www.yelp.com/biz/sidney-dairy-barn-sidney,4,6/26/2022,Nice little local place for ice cream.My favor...
2,https://www.yelp.com/biz/sidney-dairy-barn-sidney,5,8/7/2021,A delicious treat on a hot day! Staff was very...
3,https://www.yelp.com/biz/sidney-dairy-barn-sidney,4,7/28/2016,This was great service and a fun crew! I got t...
4,https://www.yelp.com/biz/sidney-dairy-barn-sidney,5,6/23/2015,This is one of my favorite places to get ice c...

In [ ]:
# vader thing
analyzer = SentimentIntensityAnalyzer()

# find polarity score of each review & add to a new df
scores = yelp['Review Text'].apply(lambda x: analyzer.polarity_scores(str(x))).apply(pd.Series)

# check sentiment scores
scores.head()

     neg    neu    pos  compound
0  0.000  0.663  0.337    0.8803
1  0.045  0.625  0.330    0.9531
2  0.000  0.624  0.376    0.9224
3  0.019  0.776  0.206    0.9400
4  0.013  0.741  0.246    0.9940

In [ ]:
# add sentiment scores to og df
yelp = pd.concat([yelp, scores], axis = 1)

# check yelp df after concat sentiment sccores
yelp.head()

,Yelp URL,Rating,Date,Review Text,neg,neu,pos,compound
0,https://www.yelp.com/biz/sidney-dairy-barn-sidney,5,1/22/2022,All I can say is they have very good ice cream...,0.000,0.663,0.337,0.8803
1,https://www.yelp.com/biz/sidney-dairy-barn-sidney,4,6/26/2022,Nice little local place for ice cream.My favor...,0.045,0.625,0.330,0.9531
2,https://www.yelp.com/biz/sidney-dairy-barn-sidney,5,8/7/2021,A delicious treat on a hot day! Staff was very...,0.000,0.624,0.376,0.9224
3,https://www.yelp.com/biz/sidney-dairy-barn-sidney,4,7/28/2016,This was great service and a fun crew! I got t...,0.019,0.776,0.206,0.9400
4,https://www.yelp.com/biz/sidney-dairy-barn-sidney,5,6/23/2015,This is one of my favorite places to get ice c...,0.013,0.741,0.246,0.9940